services:
  photo-stream:
    container_name: photo-stream
    image: photo-stream:latest
    build:
      context: .
      args:
        BASE_IMAGE: ruby:3.4-alpine
        # BASE_IMAGE: arm32v6/ruby:3.4-alpine # arm base image for RPI
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    environment:
      - TITLE=${TITLE}
      - EMAIL=${EMAIL}
      - AUTHOR_NAME=${AUTHOR_NAME}
      - AUTHOR_EMAIL=${AUTHOR_EMAIL}
      - AUTHOR_WEBSITE=${AUTHOR_WEBSITE}
      - DESCRIPTION=${DESCRIPTION}
      - BASEURL=${BASEURL}
      - URL=${URL}
      - SHOW_RSS_FEED=${SHOW_RSS_FEED}
      - SHOW_OFFICIAL_GITHUB=${SHOW_OFFICIAL_GITHUB}
      - HEADER_ENABLED=${HEADER_ENABLED}
      - HEADER_BACKGROUND_COLOR=${HEADER_BACKGROUND_COLOR}
      - TWITTER_USERNAME=${TWITTER_USERNAME}
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - INSTAGRAM_USERNAME=${INSTAGRAM_USERNAME}
      - CUSTOM_LINK_NAME=${CUSTOM_LINK_NAME}
      - CUSTOM_LINK_URL=${CUSTOM_LINK_URL}
      - DEFAULT_REVERSE_SORT=${DEFAULT_REVERSE_SORT}
      - ALLOW_ORDER_SORT_CHANGE=${ALLOW_ORDER_SORT_CHANGE}
      - ALLOW_ORIGINAL_DOWNLOAD=${ALLOW_ORIGINAL_DOWNLOAD}
      - ALLOW_INDEXING=${ALLOW_INDEXING}
      - ALLOW_IMAGE_SHARING=${ALLOW_IMAGE_SHARING}
    volumes:
      - ${PHOTO_PATH}:/photo-stream/photos
    env_file: .env
    ports:
      - "4000:4000"
    restart: unless-stopped
